# Site settings
title: P1 Graphs
email: felix.monninger Æt gmail dÆt com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog containing things I find interesting, mostly on the topics of math, programming, (studying) 中文, and P1 graphs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://p1graph.org" # the base hostname & protocol for your site
twitter_username:
github_username:  heinzelotto

# Build settings
markdown: kramdown
